use_frameworks!

target 'OnlineChatSdk_Example' do
  pod 'OnlineChatSdk', :path => '../'

  target 'OnlineChatSdk_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
